PUT http://localhost:3001/api/persons/68168cd449ec8c0a777b34b4
Content-Type: application/json

{
  "name": "Edgar Djikstra",
  "number": "23-234328745"
}

###
PUT https://phonebook-rheo.onrender.com/api/persons/68168cd449ec8c0a777b34b4
Content-Type: application/json

{
  "name": "Edgar Djikstra",
  "number": "23-234328745"
}