POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4MjkzN2E3MzZkN2I0MGY3NjRlZmIwMCIsImlhdCI6MTc0NzU0NjgzMSwiZXhwIjoxNzQ3NTUwNDMxfQ.DU9Yc8nw3QMY21OLT6Lc21g5vtXI_x8Tf74M9h8Ah8s

{
  "title": "Test Blog",
  "author": "Test Author",
  "url": "https://testblog.com",
  "likes": 0
}